### ISSUE TITLE
Create a single docker image for all components (for dockerhub)

### ISSUE THREAD

**Issue by neomatrix369** [neomatrix369/chatbot-conversations#12]
For learning and illustrating purposes it;s a good idea to have a single Docker image via single `Dockerfile`.

Then executing/implementing issues #1 to #10 will become easier. Thanks for splitting the issues into smaller parts @yugoccp 

Here are two examples to follow to create the docker config file(s) and shell scripts to achieve it:
- https://github.com/neomatrix369/awesome-ai-ml-dl/tree/master/examples/deepnetts
- https://github.com/neomatrix369/awesome-ai-ml-dl/tree/master/examples/tribuo

_(also check the `docker-image` folder)_

**Comment by neomatrix369** [comment]
@yugoccp let's do this together, I'll help you here, if we do it the above way there are multiple benefits

**Comment by neomatrix369** [comment]
If there are any branches or PRs you wish reviewing feel free to push them to Github and I can share my comments on there.

**Comment by neomatrix369** [comment]
You are also a collaborator to this project which also means we can work on the same branch or PR if necessary @yugoccp

**Comment by neomatrix369** [comment]
Just enabled the https://github.com/neomatrix369/chatbot-conversations/projects/1 project management interface so that we can keep track of issues and PRs

**Comment by yugoccp** [comment]
> You are also a collaborator to this project which also means we can work on the same branch or PR if necessary @yugoccp

Thanks @neomatrix369 ! I'll push some changes soon!

**Comment by yugoccp** [comment]
Created branch to address this issue
https://github.com/neomatrix369/chatbot-conversations/tree/feature/add-single-dockerfile

@neomatrix369 could you help me fix run container command?

**Comment by yugoccp** [comment]
@neomatrix369 in the end I make it run with helidon and quarkus worlds, will be happy to review it together, and moving forward to also run roberta-world :)

**Comment by neomatrix369** [comment]
I'll test it out on my machine and try to push something for python/roberta-world

**Comment by neomatrix369** [comment]
> @neomatrix369 in the end I make it run with helidon and quarkus worlds, will be happy to review it together, and moving forward to also run roberta-world :)

Its fixed now, there was an issue with `torch==1.3.1` in the `requirements.txt` file, this version does not exist - check the commits you can see other changes as well.
I'll briefly test it and push the changes and let you continue

**Comment by neomatrix369** [comment]
There are some python related errors, try to debug and see why its failing - there is fun in this investigation.

**Comment by yugoccp** [comment]
@neomatrix369 I've updated README.md file with instructions and fixed roberta-world dependency to work. Will open PR for review 😄
